-- h2용 스크립트 (운영 DB용과 분리 필요)

INSERT INTO TRAVEL_CATEGORY(CATEGORY_ID, CATEGORY_NAME, SORT_ORDER, REG_USER_ID, REG_DTT) VALUES (1, '카테고리1', 1, 'testUser', NOW());
INSERT INTO TRAVEL_CATEGORY(CATEGORY_ID, CATEGORY_NAME, SORT_ORDER, REG_USER_ID, REG_DTT) VALUES (2, '카테고리2', 2, 'testUser', NOW());
INSERT INTO TRAVEL_CATEGORY(CATEGORY_ID, CATEGORY_NAME, SORT_ORDER, REG_USER_ID, REG_DTT) VALUES (3, '카테고리3', 3, 'testUser', NOW());

INSERT INTO TRAVEL(TITLE, REGION, CATEGORY_ID, TRAVEL_START_DT, TRAVEL_END_DT, COST_TYPE, SEASON, VEHICLE, CONTENTS, REG_USER_ID, REG_DTT) VALUES ('제목1', 'BUSAN', 1, '20250318', '20250320', 'UNDER_100K', 'SPRING', 'WALK', '내용1', 1, NOW());
INSERT INTO TRAVEL(TITLE, REGION, CATEGORY_ID, TRAVEL_START_DT, TRAVEL_END_DT, COST_TYPE, SEASON, VEHICLE, CONTENTS, REG_USER_ID, REG_DTT) VALUES ('제목2', 'SEOUL', 2, '20250318', '20250320', 'BETWEEN_200K_300K', 'SPRING', 'PUBLIC_TRANSPORT', '내용2', 1, NOW());
INSERT INTO TRAVEL(TITLE, REGION, CATEGORY_ID, TRAVEL_START_DT, TRAVEL_END_DT, COST_TYPE, SEASON, VEHICLE, CONTENTS, REG_USER_ID, REG_DTT) VALUES ('제목3', 'INCHEON', 3, '20251201', '20251231', 'OVER_500K', 'WINTER', 'CAR', '내용3', 1, NOW());

ALTER TABLE TRAVEL_CATEGORY ALTER COLUMN CATEGORY_ID RESTART WITH 4;
ALTER TABLE TRAVEL ALTER COLUMN CATEGORY_ID RESTART WITH 4;
